# Generated by Django 5.0.6 on 2024-06-21 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$')], verbose_name='Phone Number'),
        ),
    ]
