# Generated by Django 5.0.6 on 2024-06-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('car', models.IntegerField()),
                ('temple', models.BooleanField()),
                ('garden', models.BooleanField()),
                ('living_room', models.IntegerField()),
                ('store_room', models.IntegerField()),
            ],
        ),
    ]
