# Generated by Django 5.0.6 on 2024-07-10 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_html', models.FileField(upload_to='maps/')),
                ('created_at', models.DateTimeField(default='2024-07-10T08:49:07.498834+00:00')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('car', models.IntegerField()),
                ('temple', models.IntegerField()),
                ('garden', models.IntegerField()),
                ('living_room', models.IntegerField()),
                ('store_room', models.IntegerField()),
                ('created_at', models.DateTimeField(default='2024-07-10T08:49:07.497636+00:00')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='project_files/')),
                ('avg_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default='2024-07-10T08:49:07.498277+00:00')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dummy.project')),
            ],
        ),
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(max_length=255)),
                ('ground_water_depth', models.CharField(max_length=255)),
                ('foundation_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default='2024-07-10T08:49:07.498588+00:00')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
