# Generated by Django 5.0.6 on 2024-07-10 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapfile',
            name='created_at',
            field=models.DateTimeField(default='2024-07-10T10:37:13.576252+00:00'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='created_at',
            field=models.DateTimeField(default='2024-07-10T10:37:13.575773+00:00'),
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('png_image', models.ImageField(blank=True, null=True, upload_to='pngs/')),
                ('dxf_file', models.FileField(blank=True, null=True, upload_to='dxfs/')),
                ('avg_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dummy.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectFile',
        ),
    ]
