# Generated by Django 5.0.6 on 2024-06-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='garden',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='temple',
            field=models.IntegerField(),
        ),
    ]
