# Generated by Django 5.0.6 on 2024-08-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0003_rename_area_info_userfile_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapfile',
            name='map_html',
        ),
        migrations.AddField(
            model_name='mapfile',
            name='map_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
