# Generated by Django 5.0.6 on 2024-07-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0003_userpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpdf',
            name='pdf',
            field=models.ImageField(upload_to='pdfs/'),
        ),
    ]
