# Generated by Django 5.0.6 on 2024-07-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0005_userpng_delete_userpdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpng',
            old_name='pdf',
            new_name='image',
        ),
    ]
