# Generated by Django 5.0.6 on 2024-07-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0009_alter_userfile_dxf_file_alter_userfile_png_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='avg_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
