# Generated by Django 5.0.6 on 2024-07-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0010_userfile_avg_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='avg_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
