# Generated by Django 5.0.6 on 2024-07-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0011_alter_userfile_avg_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='area_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
